# docker/Dockerfile.production

# 1. Build (compile + jar)
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY ../pom.xml ./
COPY ../src ./src

RUN mvn -B -ntp -DskipTests package

# 2. Run (image légère)
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=production

CMD ["java","-jar","app.jar"]
